# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0006_list_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(related_name='list_shared_with', related_query_name='list_shared_withs', to=settings.AUTH_USER_MODEL),
        ),
    ]
