---
- hosts: all
  vars:
      host: "{{ inventory_hostname }}"
      working_directory: "/home/{{ ansible_ssh_user }}/sites/{{ inventory_hostname }}/"

  tasks:
     - name: setup site folder
       file:
           path: "{{ working_directory }}"
           state: directory
           owner: "{{ ansible_ssh_user }}"
           mode: 0775

     - name: get latest source from master
       git:
           repo: https://github.com/dbutlerdb/python-tdd-book.git
           clone: yes
           dest: "{{ working_directory }}"
           version: master

     - name: setup python virtual environment
       pip:
           requirements: "{{ working_directory }}/requirements.txt"
           virtualenv: "{{ working_directory }}/virtualenv"
           virtualenv_python: python3.6

     - name: create .env file
       template:
           src=./env.template.j2
           dest={{ working_directory }}/.env

     - name: update static files
       django_manage:
           app_path: "{{ working_directory }}"
           command: collectstatic
           virtualenv: "{{ working_directory }}/virtualenv"

     - name: update database
       django_manage:
           app_path: "{{ working_directory }}"
           command: migrate
           virtualenv: "{{ working_directory }}/virtualenv"
